const INTERVENTION_TYPES = [
  'ARCHITECTURE_BOUNDARY',
  'RUNTIME_CONFLICT',
  'CONTRACT_BREAK',
  'CAPABILITY_GAP',
  'DEPENDENCY_RISK',
  'EVIDENCE_INVALIDATED',
  'TEST_COVERAGE_GAP',
  'UNDECLARED_FILE',
  'UNDECLARED_SCOPE',
  'HIGH_IMPACT_CHANGE',
  'UNCERTAIN_SYSTEM_AREA',
  'STALE_CONTEXT',
  'PLAN_DRIFT',
  'IMPLEMENTATION_DRIFT',
  'VERIFICATION_REQUIRED'
];

module.exports = {
  INTERVENTION_TYPES
};
